### ISSUE TITLE
Сборка проекта

### ISSUE THREAD

**Issue by Hahahayabanan** [Liquense/FSD-task-2#14]
Сейчас не собирается

![image](https://user-images.githubusercontent.com/43137324/87968511-954c4280-cad1-11ea-8917-39e7a69811bb.png)

**Comment by Liquense** [comment]
похоже на то, что не хватает плагина, который я добавлял в этом коммите:
https://github.com/Liquense/FSD-task-2/commit/1928352e3e515fa5109259f4702c440d549c49f8

`npm install` не помогает?

**Comment by Hahahayabanan** [comment]
Ты на linux сидишь? Другая ошибка)

![image](https://user-images.githubusercontent.com/43137324/88082733-3949f280-cb93-11ea-8416-b14bcb19ae62.png)

**Comment by Liquense** [comment]
на винде, видать поэтому у меня ошибки из-за регистра и не было))
проверь теперь
