### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by Hahahayabanan** [Liquense/FSD-task-2#16]
Модификатор должен быть прилагательным
По стандартам п.1. https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md

![image](https://user-images.githubusercontent.com/43137324/88415840-37309f80-cdf0-11ea-9a08-90ac21ad34a9.png)

**Comment by Hahahayabanan** [comment]
Старайся не использовать сокращения там, где нет необходимости

![image](https://user-images.githubusercontent.com/43137324/88620356-de425f00-d0ae-11ea-8608-4c362dd3e7f2.png)
![image](https://user-images.githubusercontent.com/43137324/88620435-16e23880-d0af-11ea-8b6e-fa9522aacaed.png)
![image](https://user-images.githubusercontent.com/43137324/88620482-34170700-d0af-11ea-8e9a-2a965294cdaa.png)

**Comment by Hahahayabanan** [comment]
Стоит переименовать

![image](https://user-images.githubusercontent.com/43137324/88885839-5002e000-d24a-11ea-8e29-afd4a8e7592d.png)

**Comment by Hahahayabanan** [comment]
![image](https://user-images.githubusercontent.com/43137324/89116429-fc400300-d4a4-11ea-9c9c-0c5e92483d2d.png)

**Comment by Hahahayabanan** [comment]
Слижком уж длинное имя

![image](https://user-images.githubusercontent.com/43137324/89116480-9ef88180-d4a5-11ea-94c9-4114e55754b6.png)

**Comment by Hahahayabanan** [comment]
Тоже длинное название

![image](https://user-images.githubusercontent.com/43137324/89116874-f26cce80-d4a9-11ea-981c-ab64f35e43aa.png)

**Comment by Hahahayabanan** [comment]
Кстати, не заметил сразу миксины pug, как и css, именуются нотацией `kebab-case`

**Comment by Hahahayabanan** [comment]
И названия блока везде должны совпадать
Тут можно и без `block`

![image](https://user-images.githubusercontent.com/43137324/89116933-7b840580-d4aa-11ea-8345-78c59cc5c2ef.png)

**Comment by Liquense** [comment]
> Очень странное именование. Не лучше им быть блоками?
> 
> ![image](https://user-images.githubusercontent.com/43137324/90958853-f76cde80-e4a7-11ea-81f0-f2c4f09d6f4b.png)

просто это по-сути области страницы, которые только в ней и используются, показалось логичным делать это элементами, БЭМ вроде позволяет
![image](https://user-images.githubusercontent.com/20877460/91452490-d55ccd00-e8a8-11ea-972c-691e7db36031.png)

**Comment by Hahahayabanan** [comment]
Метод возвращает булево значение, и именоваться должен соответственно
https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#variable-naming--boolean

![image](https://user-images.githubusercontent.com/43137324/92146852-609b0d00-ee2b-11ea-8926-3b890cbec910.png)

**Comment by Liquense** [comment]
забыл вынести в отдельный коммит, правка в https://github.com/Liquense/FSD-task-2/commit/cbd2f96c930611bc9ddd593c2a03f75f7bc95b33

**Comment by Hahahayabanan** [comment]
В английском языке, вроде как, прилагательное идёт перед существительным

![image](https://user-images.githubusercontent.com/43137324/93503508-3b2cf980-f929-11ea-9d8d-fab1b492eab3.png)

**Comment by Hahahayabanan** [comment]
![image](https://user-images.githubusercontent.com/43137324/93503741-9363fb80-f929-11ea-8c09-3012ab348724.png)

**Comment by Hahahayabanan** [comment]
Странное слово

![image](https://user-images.githubusercontent.com/43137324/93504050-fce40a00-f929-11ea-9497-c0018710f9b6.png)

**Comment by Hahahayabanan** [comment]
"Строки содержимого"

![image](https://user-images.githubusercontent.com/43137324/93733379-2fba2680-fbe6-11ea-8d7e-88c70080ef2b.png)

**Comment by Hahahayabanan** [comment]
А какой здесь контент? Картинки? Можно так и назвать images

![image](https://user-images.githubusercontent.com/43137324/93733746-bd4a4600-fbe7-11ea-8e4a-d46e8d83db51.png)

Тогда тут не element, а image

![image](https://user-images.githubusercontent.com/43137324/93733767-d3f09d00-fbe7-11ea-8363-2985ede5b1aa.png)

**Comment by Hahahayabanan** [comment]
Я думаю стоит пересмотреть имена данных цветов. Выглядит громоздко и сложно, плюс имя связано со значением css свойства

![image](https://user-images.githubusercontent.com/43137324/93735320-9ee74900-fbed-11ea-9441-cc51fe8e9d3f.png)

**Comment by Hahahayabanan** [comment]
Тут уже всё говорит о том, что два инпута, можно так и передавать не массив, а первый лайаут, второй

![image](https://user-images.githubusercontent.com/43137324/93735691-db677480-fbee-11ea-8dd0-306fe0a7dc14.png)

**Comment by Hahahayabanan** [comment]
`range` существительное

![image](https://user-images.githubusercontent.com/43137324/93737140-6ea2a900-fbf3-11ea-8945-13454de5710e.png)

**Comment by Hahahayabanan** [comment]
Может так и сделать параметры min и max? А то не очевидно передавать просто элементы массива

![image](https://user-images.githubusercontent.com/43137324/93737226-ad386380-fbf3-11ea-868a-996f348f2680.png)
