### ISSUE TITLE
Многофункциональный блок

### ISSUE THREAD

**Issue by Hahahayabanan** [Liquense/FSD-task-2#18]
Так это radio, toggle, like или checkbox? Думаю стоит разделить эти сущности

![image](https://user-images.githubusercontent.com/43137324/88418112-1d915700-cdf4-11ea-90de-994a5070ee82.png)

**Comment by Hahahayabanan** [comment]
Кстати, а зачем понадобилось использовать jQuery плагин для чекбокса? Довольно простой же блок, можно сделать и без js

**Comment by Liquense** [comment]
> Кстати, а зачем понадобилось использовать jQuery плагин для чекбокса? Довольно простой же блок, можно сделать и без js

по-моему мне тогда показалось, что их версия кастомизируется достаточно гибко и так будет быстрее, поскольку их ui-либа уже использована была на слайдере, и далеко идти не пришлось

**Comment by Hahahayabanan** [comment]
Всё же считаю, если можно обойтись без js, то стоит так и делать, это увеличивает сложность и неочевидность поведения. Блоки checkbox, radio, toggle

**Comment by Hahahayabanan** [comment]
Тоже универсальный блок, сложно понять что он делает. Я так понял это блок, реализующий `Expandable Checkbox List`?
Так пусть он только этим и занимается, не нужно его использовать, чтобы расположить рядом и `radio`, и `toggle`. Для этого будет достаточно просто флекс контейнера

![image](https://user-images.githubusercontent.com/43137324/88886120-de776180-d24a-11ea-94a9-2ae6440d2130.png)
