### ISSUE TITLE
Вложенность элементов

### ISSUE THREAD

**Issue by Hahahayabanan** [Liquense/FSD-task-2#20]
Согласно спецификации внутри тега `a` не должно быть интерактивных элементов

https://developer.mozilla.org/ru/docs/Web/HTML/Element/A
![image](https://user-images.githubusercontent.com/43137324/88619015-92da8180-d0ab-11ea-8569-056dd7ba6c85.png)

**Comment by Liquense** [comment]
а, я по этому ориентировался, там вроде бы про исключение интерактивных не сказано http://w3c.github.io/html-reference/a.html
исправлю
