### ISSUE TITLE
Повторная инициализация

### ISSUE THREAD

**Issue by Hahahayabanan** [Liquense/FSD-task-2#21]
Стоит делать селект и инициализацию блоков в файле init.js, конечно, за исключением случаев, если они используются только в других блоках. А то, сейчас получается, что ты вызываешь инициализацию в нескольких местах

![image](https://user-images.githubusercontent.com/43137324/88886693-1a5ef680-d24c-11ea-97ca-857afd07cc66.png)

**Comment by Liquense** [comment]
разве не нужно в карточке осуществлять инициализацию внутренностей на случай использования её отдельно где-нибудь?

а страницы - это разные энтри-поинты, так что там по одному разу происходит инициализация своих блоков (тот же список нужен не везде)

да и инициализация безопасная: если объект инициализирован, то возвращается существующий экземпляр
