### ISSUE TITLE
Mixes

### ISSUE THREAD

**Issue by Hahahayabanan** [Liquense/FSD-task-2#3]
По стандартам

> 5. Кастомизировать компоненты только через модификаторы, никаких примесей.

https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md

![image](https://user-images.githubusercontent.com/43137324/82881465-cafd0100-9f50-11ea-9662-ac07a9c7f49c.png)

**Comment by Liquense** [comment]
то есть шрифты лучше навешивать scss-миксином, а не классом?

**Comment by Hahahayabanan** [comment]
> то есть шрифты лучше навешивать scss-миксином, а не классом-примесью?

Да, если хочешь, можешь scss-миксином сделать

Классовых миксов не должно быть совсем
![image](https://user-images.githubusercontent.com/43137324/86205574-4585f580-bb7b-11ea-8f25-8d156ce66ec8.png)

**Comment by Hahahayabanan** [comment]
![image](https://user-images.githubusercontent.com/43137324/86207263-34d77e80-bb7f-11ea-8433-d6b46edbd2f7.png)
