### ISSUE TITLE
Параметры блоков

### ISSUE THREAD

**Issue by Hahahayabanan** [Liquense/FSD-task-2#6]
Параметры для блока в любом случае лучше передавать в виде объекта, даже если параметр один. Иначе, когда их будет нужно изменить, придётся это делать везде, где этот блок был использован.

![image](https://user-images.githubusercontent.com/43137324/82884209-7d829300-9f54-11ea-8c30-b6eb70f7f551.png)

**Comment by Hahahayabanan** [comment]
`addClasses` не правильно добавлять какие-то классы блоку "из вне"
Если нужно передать какое-то состояние, лучше сделать это модификатором

**Comment by Hahahayabanan** [comment]
Снова у блока параметр, который формирует класс. Проверь во всём проекте
![image](https://user-images.githubusercontent.com/43137324/84180139-13abd280-aa98-11ea-85fd-74bdf18653c4.png)

**Comment by Hahahayabanan** [comment]
Деструктурировать объект можно прямо в параметрах миксина, там же задать значения по-умолчанию

![image](https://user-images.githubusercontent.com/43137324/86206364-428c0480-bb7d-11ea-9422-0e8a0f408b50.png)

Почему везде `var`?)

**Comment by Liquense** [comment]
> Почему везде `var`?)

почему-то с let и const у .pug файлов подсветка криво работать начинает у объявленных переменных/констант

**Comment by Hahahayabanan** [comment]
Добавь ещё в параметры блока значение по умолчанию для объекта `= {}`, на случай, когда миксин используется без атрибутов
